spring:
  redis:
    port: 6379
    host: localhost
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hmdp?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: zyx
  rabbitmq:
    host: 192.168.88.128
    port: 5672
    virtual-host: /
    username: ezhixuan
    password: 123456
mybatis-plus:
  configuration:
    log-prefix: com.hmdp.log
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8080